import {randomUUID} from 'node:crypto';
import {ClickUpClient} from './clickup.mjs';import {SCOPE} from './config.mjs';import {taskScope} from './scope.mjs';import {normalizeFilter,DEFAULT_FILTER} from './filters.mjs';
export function location(entry,workflow){return {...taskScope({workspaceId:SCOPE.workspaceId,spaceId:entry.space_id,spaceName:entry.space_name,listId:entry.id,listName:entry.name}),workflow};}
export function selectedLists(catalog,filter){const f=normalizeFilter(filter);if(f.list_ids.some(id=>!catalog.lists.some(l=>l.id===id))||f.space_ids.some(id=>!catalog.spaces.some(s=>s.id===id)))throw Error('A selected ClickUp list or space is no longer accessible. Refresh the list directory.');return catalog.lists.filter(l=>(!f.list_ids.length||f.list_ids.includes(l.id))&&(!f.space_ids.length||f.space_ids.includes(l.space_id)));}
export async function queryBoard(store,token,requested,{fetcher=fetch,refreshCatalog=false}={}){
 const before=await store.read();if(before.retry_at&&Date.now()<Date.parse(before.retry_at))throw Error('ClickUp is rate limited. Wait before retrying.');const filter=normalizeFilter(requested||before.filter||DEFAULT_FILTER),request=randomUUID();await store.mutate(s=>{s.query_request=request;});
 try{
  const root=new ClickUpClient(token,fetcher);const catalog=refreshCatalog||!before.catalog?await root.catalog():structuredClone(before.catalog);const lists=selectedLists(catalog,filter),tickets=new Map(),started=Date.now();
  if(lists.length>1){for(const t of await root.workspaceTasks(catalog,lists))tickets.set(t.id,t);}else for(const list of lists){const client=new ClickUpClient(token,fetcher,location(list,before.workflows?.[list.id]));for(const t of await client.tasks(catalog)){const old=tickets.get(t.id);if(old)t.source_list_ids=[...new Set([...old.source_list_ids,...t.source_list_ids])];tickets.set(t.id,t);}}
  return (await store.mutate(s=>{if(s.query_request!==request)return;s.ticket_records??={};for(const t of s.tickets)s.ticket_records[t.id]??={...t};s.tickets=[...tickets.values()].map(t=>{const old=s.ticket_records[t.id]||s.tickets.find(x=>x.id===t.id),run=s.runs[t.id];if(old&&Date.parse(run?.clickup_synced_at)>started)Object.assign(t,{status:old.status,finished:old.finished});s.ticket_records[t.id]={...t};return t;});s.catalog=catalog;const changed=JSON.stringify(s.filter)!==JSON.stringify(filter);s.filter=filter;if(changed)s.active_preset=null;s.fetched_at=new Date().toISOString();s.complete=true;s.error=null;s.setup_error=null;s.connection_verified_at=s.fetched_at;s.connection_required=false;s.retry_at=null;})).state;
 }catch(e){await store.mutate(s=>{if(s.query_request!==request)return;s.error=e.message;s.connection_required=e.kind==='authentication';s.retry_at=e.retryAfter?new Date(Date.now()+e.retryAfter).toISOString():null;});throw e;}
}

