import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Repository,command} from './github.mjs';import {SCOPE} from './config.mjs';
const root=await mkdtemp(join(tmpdir(),'puppeteer-git-cleanup-')),bare=join(root,'remote.git'),local=join(root,'local');await mkdir(local);
const git=(args,cwd=local)=>command('git',args,{cwd});await git(['init','--bare',bare],root);await git(['init']);await git(['config','user.name','Fixture']);await git(['config','user.email','fixture@example.invalid']);await git(['remote','add','origin',bare]);await writeFile(join(local,'fixture.txt'),'fixture');await git(['add','fixture.txt']);await git(['commit','-m','Fixture']);await git(['branch','-M','develop']);await git(['push','origin','develop']);
const branch='fix/cu-fixture-cleanup';await git(['switch','-c',branch]);await writeFile(join(local,'fixture.txt'),'fixed');await git(['commit','-am','Fixed']);const sha=await git(['rev-parse','HEAD']);await git(['push','origin',branch]);
// Route only this fixture's advertised URL to its disposable bare repository.
const run=(exe,args,options)=>{if(args[0]==='remote')return Promise.resolve(SCOPE.repositoryUrl);return command(exe,args.map(a=>a===SCOPE.repositoryUrl?bare:a),{...options,cwd:options.cwd===SCOPE.repositoryPath?local:options.cwd});};
const repository=new Repository({run,path:local});await repository.cleanup('fixture',{branch,sha},branch);assert.equal(await git(['ls-remote','--heads','origin',`refs/heads/${branch}`]),'');assert.equal(await git(['for-each-ref','--format=%(objectname)',`refs/heads/${branch}`]),'');assert.equal(await git(['rev-parse','HEAD']),sha);assert.equal(await git(['status','--porcelain']),'');
// Direct delivery must be proven on the fetched develop ref.
await assert.rejects(()=>repository.directDelivery(sha,branch),/not contained/);await git(['push','origin','HEAD:develop']);assert.equal((await repository.directDelivery(sha,branch)).direct,true);
console.log('PASS: native Git cleanup against a disposable bare remote, checked-out clean branch detached without file changes, remote/local refs deleted, and direct-delivery ancestry verified.');
