import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from './store.mjs';import {finishBug} from './finish.mjs';import {Repository} from './github.mjs';import {ClickUpClient} from './clickup.mjs';import {SCOPE} from './config.mjs';import {codingPrompt} from './dispatch.mjs';
const url='https://github.com/example-owner/ExampleProject/pull/6',sha='a'.repeat(40),branch='fix/cu-fixture-stops';
const pr={url,sha,branch,merged_at:'2026-10-01T10:00:00Z'};
async function fixture({merged=true,dirty=false,uncertain=false}={}){const store=new Store(await mkdtemp(join(tmpdir(),'puppeteer-finish-')));await store.mutate(s=>{s.tickets=[{id:'fixture',status:'review requested',finished:false}];s.runs.fixture={launch_id:'test',status:'review_requested',pr_url:url,branch};});let posts=0,completions=0,cleanups=0,comments=[];
 const client={verifyTicket:async()=>({status:{status:completions?'complete':'review requested',type:completions?'done':'custom'}}),comments:async()=>comments,postAcceptance:async(id,text)=>{posts++;if(uncertain)throw Error('uncertain transport');comments=[{id:'1',text}];return '1';},finishBug:async()=>{completions++;return {status:'complete',finished:true};}};
 const repo={pullRequest:async()=>{if(!merged)throw Error('PR is still open');return pr;},cleanup:async()=>{cleanups++;if(dirty)throw Error('Uncommitted files preserved');return 'deleted';}};
 const run=()=>finishBug(store,{ticket_id:'fixture',expected_status:completions?'complete':'review requested',confirmed_tested:true},client,repo);
 return {run,store,counts:()=>({posts,completions,cleanups}),setComments:c=>{comments=c;}};
}
let f=await fixture({merged:false});let s=await f.run();assert.match(s.runs.fixture.finish_error,/still open/);assert.deepEqual(f.counts(),{posts:0,completions:0,cleanups:0});assert.equal(s.tickets[0].finished,false);
f=await fixture();s=await f.run();assert.equal(s.tickets[0].finished,true);assert.equal(s.runs.fixture.finish.cleanup_done,true);await f.run();assert.equal(f.counts().posts,1);
f=await fixture({dirty:true});s=await f.run();assert.equal(s.tickets[0].finished,true);assert.match(s.runs.fixture.finish_error,/preserved/);assert.equal(f.counts().posts,1);
f=await fixture({uncertain:true});await f.run();s=await f.run();assert.equal(f.counts().posts,1);assert.equal(f.counts().completions,0);assert.match(s.runs.fixture.finish_error,/uncertain outcome/);f.setComments([{id:'recovered',text:`[Puppeteer Bugs acceptance: ${url}]`}]);s=await f.run();assert.equal(s.tickets[0].finished,true);assert.equal(f.counts().posts,1);
// Exercise Git command boundaries and credentials without any real GitHub writes.
let gitCalls=[],dirty=false,moved=false,remoteExists=true,localExists=true,attached=true;
const run=async(exe,args,opt)=>{gitCalls.push(args);assert.equal(exe,'git');if(args[0]==='remote')return SCOPE.repositoryUrl;if(args[0]==='credential')return 'password=synthetic-secret';if(args[0]==='ls-remote')return remoteExists?`${moved?'b'.repeat(40):sha}\trefs/heads/${branch}`:'';if(args[0]==='push'){assert.ok(args.includes(`--force-with-lease=refs/heads/${branch}:${sha}`));remoteExists=false;return '';}
 if(args[0]==='for-each-ref')return args.at(-1).startsWith('refs/remotes/')?'':localExists?sha:'';if(args[0]==='worktree')return attached?`worktree C:/fixture\nHEAD ${sha}\nbranch refs/heads/${branch}\n`:'';if(args[0]==='status')return dirty?' M file':'';if(args[0]==='rev-parse')return sha;if(args[0]==='switch'){assert.deepEqual(args,['switch','--detach',sha]);attached=false;return '';}
 if(args[0]==='update-ref'){assert.deepEqual(args,['update-ref','-d',`refs/heads/${branch}`,sha]);localExists=false;return '';}if(args[0]==='check-ref-format')return '';throw Error('Unexpected git command '+args[0]);};
const api={number:6,html_url:url,merged:true,merged_at:pr.merged_at,state:'closed',base:{ref:'develop',repo:{full_name:'example-owner/ExampleProject'}},head:{ref:branch,sha,repo:{full_name:'example-owner/ExampleProject'}}};
const repository=new Repository({run,fetcher:async(u,o)=>{assert.equal(u,'https://api.github.com/repos/example-owner/ExampleProject/pulls/6');assert.equal(o.headers.Authorization,'Bearer synthetic-secret');return Response.json(api);}});
assert.equal((await repository.pullRequest(url)).sha,sha);api.merged=false;await assert.rejects(()=>repository.pullRequest(url),/closed without/);api.state='open';await assert.rejects(()=>repository.pullRequest(url),/still open/);api.merged=true;api.base.ref='main';await assert.rejects(()=>repository.pullRequest(url),/target branch/);api.base.ref='develop';
await repository.cleanup('fixture',pr,branch);assert.equal(remoteExists,false);assert.equal(localExists,false);await repository.cleanup('fixture',pr,branch);
remoteExists=true;localExists=true;attached=true;moved=true;await assert.rejects(()=>repository.cleanup('fixture',pr,branch),/beyond/);assert.equal(remoteExists,true);moved=false;dirty=true;await assert.rejects(()=>repository.cleanup('fixture',pr,branch),/uncommitted/);assert.equal(localExists,true);assert.equal(attached,true);
await assert.rejects(()=>repository.cleanup('other-ticket',pr,branch),/identity/);
// Paginated task comments and threaded replies are all included as untrusted evidence.
let pages=0;const client=new ClickUpClient('fake',async(u,o)=>{if(u.pathname.endsWith('/space'))return Response.json({spaces:[{id:SCOPE.spaceId,name:SCOPE.spaceName}]});if(u.pathname.includes('/list/'))return Response.json({id:SCOPE.listId,name:SCOPE.listName,space:{id:SCOPE.spaceId},statuses:[]});if(u.pathname.endsWith('/fixture'))return Response.json({id:'fixture',list:{id:SCOPE.listId},space:{id:SCOPE.spaceId},team_id:SCOPE.workspaceId});if(u.pathname.endsWith('/reply'))return Response.json({comments:[{id:'3',date:'300',comment_text:'Reply evidence',user:{username:'Tester'}}]});pages++;if(pages===1)return Response.json({comments:[{id:'2',date:'200',comment_text:'New evidence',reply_count:1}]});if(pages===2){assert.equal(u.searchParams.get('start_id'),'2');return Response.json({comments:[{id:'1',date:'100',comment:[{text:'Older evidence'}]}]});}return Response.json({comments:[]});});
const comments=await client.comments('fixture');assert.deepEqual(comments.map(c=>c.id),['1','2','3']);assert.equal(comments[2].parent_id,'2');const prompt=codingPrompt({id:'fixture',name:'Test',comments},'launch');assert.ok(prompt.includes('Older evidence'));assert.ok(prompt.includes('Reply evidence'));assert.ok(prompt.includes('untrusted ClickUp evidence'));
console.log('PASS: merged-only completion, no writes for open/closed-unmerged PRs, acceptance deduplication and uncertain-write recovery, retryable cleanup, branch SHA guards, safe clean-worktree detachment, dirty-worktree preservation, pagination/replies, comments in prompts.');
