import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {ClickUpClient} from './clickup.mjs';import {SCOPE} from './config.mjs';import {Store} from './store.mjs';import {queryBoard,location} from './board.mjs';import {normalizeFilter,filterTickets,presets} from './filters.mjs';import {reserveLaunches,recordWork} from './dispatch.mjs';import {syncWorkStage} from './sync.mjs';import {clientScope} from './scope.mjs';
const extra={id:'12345',name:'Features',space_id:'54321',space_name:'Gameplay',folder_name:'Implementation',statuses:[{status:'Backlog',type:'open'},{status:'Doing',type:'custom'},{status:'Review',type:'custom'},{status:'Done',type:'done'}]};
const bugList={id:SCOPE.listId,name:'Bugs',space_id:SCOPE.spaceId,space_name:SCOPE.spaceName,statuses:[{status:'to do',type:'open'},{status:'in progress',type:'custom'},{status:'review requested',type:'custom'},{status:'complete',type:'done'}]};const art={id:'44444',name:'Art tasks',space_id:'33333',space_name:'Art',statuses:extra.statuses};const lists=[bugList,extra,art];let workspacePages=0,writes=[],status='Backlog';
const raw=(id,list,options={})=>({id,name:'Task '+id,team_id:SCOPE.workspaceId,list:{id:list.id},space:{id:list.space_id},status:{status:list.id===extra.id?status:'to do',type:'open'},markdown_description:'Full task evidence',assignees:[{id:7,username:'Me'}],tags:[{name:'ready'}],priority:{priority:'high'},due_date:String(Date.UTC(2026,9,1,12)),date_created:String(Date.UTC(2026,8,30)),date_updated:String(Date.UTC(2026,9,1)),custom_fields:[{id:'field',name:'Area',type:'drop_down',value:1,type_config:{options:[{id:'option',name:'Gameplay',orderindex:1}]}}],...options});
const fetcher=async(url,opt)=>{const path=url.pathname.replace('/api/v2/','');if(opt.method==='PUT'){writes.push({path,body:JSON.parse(opt.body)});status=JSON.parse(opt.body).status;return Response.json({});}
 if(path==='user')return Response.json({user:{id:7,username:'Me'}});if(path==='team')return Response.json({teams:[{id:SCOPE.workspaceId,members:[{user:{id:7,username:'Me'}},{user:{id:8,username:'Other'}}]}]});if(path.endsWith('/space'))return Response.json({spaces:lists.map(l=>({id:l.space_id,name:l.space_name}))});
 if(path==='space/54321/folder')return Response.json({folders:[{id:'999',name:'Implementation'}]});if(/^space\/\d+\/folder$/.test(path))return Response.json({folders:[]});if(path==='folder/999/list')return Response.json({lists:[{...extra,id:extra.id}]});if(/^space\/\d+\/list$/.test(path))return Response.json({lists:lists.filter(l=>l.space_id===path.split('/')[1]&&l.id!==extra.id).map(l=>({...l,space:{id:l.space_id}}))});
 if(/^list\/\d+$/.test(path)){const list=lists.find(l=>l.id===path.split('/')[1]);return Response.json({...list,space:{id:list.space_id}});}
 if(path==='task/feature')return Response.json(raw('feature',extra));if(/^list\/\d+\/task$/.test(path)){const l=lists.find(l=>l.id===path.split('/')[1]);return Response.json({tasks:[raw(l.id===extra.id?'feature':'bug',l)],last_page:true});}
 if(path===`team/${SCOPE.workspaceId}/task`){workspacePages++;assert.equal(url.searchParams.get('include_closed'),'true');assert.equal(url.searchParams.getAll('list_ids[]').length,3);return Response.json(Number(url.searchParams.get('page'))===0?{tasks:[raw('feature',extra),raw('bug',bugList),raw('art',art,{assignees:[]})],last_page:false}:{tasks:[],last_page:true});}
 if(path==='task/feature/comment')return Response.json({comments:[]});throw Error('Unexpected fixture URL '+path);
};
const client=new ClickUpClient('fixture',fetcher),catalog=await client.catalog();assert.equal(catalog.lists.length,3);assert.equal(catalog.me.id,'7');assert.equal(catalog.members.length,2);assert.equal(catalog.lists.find(l=>l.id===extra.id).folder_name,'Implementation');
const store=new Store(await mkdtemp(join(tmpdir(),'puppeteer-filter-')));await store.mutate(s=>{s.catalog=catalog;});let state=await queryBoard(store,'fixture',{list_ids:[],assignee:'me',priorities:['high'],tags:['ready']},{fetcher});assert.equal(workspacePages,2);let filtered=filterTickets(state.tickets,state.filter,catalog.me.id);assert.deepEqual(new Set(filtered.map(t=>t.id)),new Set(['feature','bug']));
for(const [filter,count] of [[{assignee:'unassigned'},1],[{assignee:'users',assignee_ids:['8']},0],[{due_from:'2026-10-01',due_to:'2026-10-01'},3],[{due_from:'2026-10-02'},0],[{tags:['ready','missing'],tag_mode:'all'},0],[{tags:['ready','missing'],tag_mode:'any'},3],[{custom:[{field_id:'field',operator:'equals',value:'Gameplay'}]},3],[{custom:[{field_id:'field',operator:'equals',value:'Other'}]},0]])assert.equal(filterTickets(state.tickets,{list_ids:[],...filter},'7').length,count);
assert.throws(()=>normalizeFilter({due_from:'2026-10-02',due_to:'2026-10-01'}));assert.throws(()=>normalizeFilter({list_ids:['bad']}));await assert.rejects(()=>queryBoard(store,'fixture',{list_ids:['111111']},{fetcher}),/no longer accessible/);assert.equal((await store.read()).tickets.length,3);
state=await queryBoard(store,'fixture',{list_ids:[extra.id]},{fetcher});const ticket=state.tickets[0];ticket.comments=[{text:'Important feature comment'}];const reserved=await reserveLaunches(store,[ticket],['feature']);const launch=reserved.value.launches[0];assert.equal(launch.scope.listId,extra.id);assert.ok(launch.prompt.includes('Gameplay (54321), List Features (12345)'));assert.ok(launch.prompt.includes('Important feature comment'));
await store.mutate(s=>{s.workflows={[extra.id]:{in_progress:'Doing',review_requested:'Review',complete:'Done'}};});await queryBoard(store,'fixture',{list_ids:[SCOPE.listId]},{fetcher});await recordWork(store,{ticket_id:'feature',launch_id:launch.launch_id,status:'in_progress'});
state=await syncWorkStage(store,'feature',launch.launch_id,async()=>new ClickUpClient('fixture',fetcher,{...clientScope(await store.read(),'feature'),workflow:(await store.read()).workflows[extra.id]}));assert.equal(state.tickets[0].id,'bug');assert.equal(state.ticket_records.feature.status,'Doing');assert.equal(writes.at(-1).path,'task/feature');assert.equal(state.runs.feature.scope.listId,extra.id);
await assert.rejects(()=>new ClickUpClient('fixture',async(u,o)=>{if(u.pathname.endsWith('/feature'))return Response.json({...raw('feature',extra),list:{id:SCOPE.listId}});return fetcher(u,o);},location(extra)).verifyTicket('feature'),/scope mismatch/);
const scoped=new ClickUpClient('fixture',fetcher,{...location(extra),workflow:{in_progress:'Doing',review_requested:'Review',complete:'Done'}});await scoped.setWorkStage('feature','review requested');await scoped.setWorkStage('feature','in progress');assert.equal(status,'Review');assert.deepEqual(await scoped.finishBug('feature','Review'),{status:'Done',finished:true});
// A slow old query may not replace a newer selection.
let resume,entered;const waitEntered=new Promise(r=>entered=r),waitResume=new Promise(r=>resume=r);const delayed=async(u,o)=>{if(u.pathname===`/api/v2/list/${extra.id}/task`){entered();await waitResume;}return fetcher(u,o);};const slow=queryBoard(store,'fixture',{list_ids:[extra.id]},{fetcher:delayed});await waitEntered;await queryBoard(store,'fixture',{list_ids:[SCOPE.listId]},{fetcher});resume();await slow;assert.equal((await store.read()).filter.list_ids[0],SCOPE.listId);
await store.mutate(s=>{s.presets=[{id:'saved',name:'My features',filter:normalizeFilter({list_ids:[extra.id],assignee:'me'})}];});assert.equal(presets(await new Store(store.directory).read()).find(p=>p.id==='saved').filter.assignee,'me');
console.log('PASS: workspace hierarchy/folder discovery, authenticated Me, cross-list pagination, compound/date/custom field filters, persistent presets, immutable session scopes, workflow mappings, updates after view changes, mismatch rejection, and stale-query protection.');
